### PR TITLE
Submitting group repo from Hug & High Five

### PR DESCRIPTION
**Pull request by Chaldeaaa**

### CODE REVIEW

**Review by pentonre — APPROVED** [review]
Approved

**Review by pentonre — APPROVED** [review]
Approved

**Comment by Chaldeaaa** [comment]
Dr. Penton, I think this pull request is approved but not yet merged on the main branch. I cannot update the QR code of the poster to the main branch, since the repo is not merged yet. So I leave the QR to be the link to my forked branch. 

Also, I have no [write access](https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github) so maybe it's on the repository owner's end to perform auto merging. 
@pentonre

**Comment by pentonre** [comment]
Hi,

I just gave you write access--I don't think you had provided your e-mail address in the document I used to give folks access.  Now you should be able to fix what is going on.

Take care,
Dr. Penton


--

Rachel E. Penton, PhD (she/her)
Teaching Associate Professor, Department of Psychology and Neuroscience
Director of Undergraduate Neuroscience Advising
University of North Carolina at Chapel Hill
231 Davie Hall, Chapel Hill, NC 27599
https://unc.zoom.us/my/pentonre

Book NSCI Major/Minor advising appointments here: https://calendly.com/pentonre/advising
If you don't see available appointments, all appointments for the next 3 weeks are already booked.  Please check back, because new appointments open up every week.
________________________________

**Comment by Chaldeaaa** [comment]
Thank you! It's now merged.

**Pull request merged**
